sudo: required
dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get install -qq texlive texlive-latex-extra

script:
- pdflatex Info_3_Skript_WS2015-16
- pdflatex Info_3_Skript_WS2015-16

